input_dir: ../../Riot/
output_dir: ../../Riot/Generated/
ib:  
  - inputs: 
    - Modules/KeyBackup/
    outputs:
      - templateName: scenes-swift4
        output: Storyboards.swift
strings:
  inputs: Assets/en.lproj/Vector.strings
  outputs:
    - templatePath: Templates/Strings/flat-swift4-vector.stencil
      output: Strings.swift
      params:
        enumName: VectorL10n
xcassets:  
  - inputs:
      - Assets/Images.xcassets
      - Assets/Caritas/Caritas Messenger-SharedImages.xcassets
      - Assets/AMP Chat/AMP Chat-SharedImages.xcassets
    outputs:
      - templateName: swift4
        output: Images.swift
plist:
  - inputs:
      - Assets/Caritas/Caritas Messenger-Defaults.plist
      - Assets/AMP Chat/AMP Chat-Defaults.plist
    outputs:
        templateName: runtime-swift4
        output: App-Defaults.swift
        params:
            enumName: AppDefaults
